/*
insert license info here
*/
using System;
using System.Collections;
using System.Data.Entity;
using System.Text;

namespace ProjetoProcessoSeletivo.NhibernateMappingFiles
{
    ///// <summary>
    /////	Generated by MyGeneration using the NHibernate Object Mapping template
    ///// </summary>
    //[Serializable]
    //public sealed  class Categoria
    //{

    //    #region Private Members
    //    private bool isChanged;

    //    private long idcategoria; 
    //    private string descricaocategoria; 
    //    private long idcategoriapai; 		
    //    #endregion

    //    #region Default ( Empty ) Class Constuctor
    //    /// <summary>
    //    /// </summary>
    //    public Categoria()
    //    {
    //        idcategoria = 0; 
    //        descricaocategoria = String.Empty; 
    //        idcategoriapai = 0; 
    //    }
    //    #endregion // End of Default ( Empty ) Class Constuctor

    //    #region Required Fields Only Constructor
    //    /// <summary>
    //    /// required (not null) fields only constructor
    //    /// </summary>
    //    public Categoria(
    //        string descricaocategoria)
    //        : this()
    //    {
    //        descricaocategoria = descricaocategoria;
    //        idcategoriapai = 0;
    //    }
    //    #endregion // End Required Fields Only Constructor

    //    #region Public Properties
			
    //    /// <summary>
    //    /// 
    //    /// </summary>
    //    public long IdCategoria
    //    {
    //        get { return idcategoria; }
    //        set
    //        {
    //            isChanged |= ( idcategoria != value ); 
    //            idcategoria = value;
    //        }

    //    }
			
    //    /// <summary>
    //    /// 
    //    /// </summary>
    //    public string DescricaoCategoria
    //    {
    //        get { return descricaocategoria; }

    //        set	
    //        {	
    //            if( value == null )
    //                throw new ArgumentOutOfRangeException("Null value not allowed for DescricaoCategoria", value, "null");
				
    //            if(  value.Length > 150)
    //                throw new ArgumentOutOfRangeException("Invalid value for DescricaoCategoria", value, value.ToString());
				
    //            isChanged |= (descricaocategoria != value); descricaocategoria = value;
    //        }
    //    }
			
    //    /// <summary>
    //    /// 
    //    /// </summary>
    //    public long IdCategoriaPai
    //    {
    //        get { return idcategoriapai; }
    //        set
    //        {
    //            isChanged |= ( idcategoriapai != value ); 
    //            idcategoriapai = value;
    //        }

    //    }
			
    //    /// <summary>
    //    /// Returns whether or not the object has changed it's values.
    //    /// </summary>
    //    public  bool IsChanged
    //    {
    //        get { return isChanged; }
    //    }
				
    //    #endregion 
    //}

    public class Categoria
    {
        public virtual Int64 idCategoria { get; set; }
        public virtual string DescricaoCategoria { get; set; }
        public virtual Int64 idCategoriaPai { get; set; }
    }
}
